import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Deck as DeckComponent} from './../components/deck'
import { Deck as DeckLibrary } from './../lib/deck'

export default function Home(props) {
  return (<>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className = {styles.home}>
        <div className={styles.cards}>
          <h1>{props.title}</h1>
          <DeckComponent cards={props.table} title='Table' flipped='2'>
            {/* <h2>Table</h2> */}
          </DeckComponent>
          <DeckComponent cards={props.hand} title='Hand' flipped='2'>
            {/* <h2>Hand</h2> */}
          </DeckComponent>
        </div>
      </div>

  </>)
}

export async function getServerSideProps(context){
  // const deck = new DeckLibrary()
  // const table = deck.dispatchCards(5)
  // const hand = deck.dispatchCards(2)

  const { data } = await (await fetch('http://localhost:4000', {
    method: 'POST',
    headers: {
      'Content-Type' : 'application/json'
    },
    body: JSON.stringify({
      query:`
        query {
          table{
            number
            symbol
          }
        }`})
  })).json()

  const handData = await (await fetch('http://localhost:4000', {
    method: 'POST',
    headers: {
      'Content-Type' : 'application/json'
    },
    body: JSON.stringify({
      query:`
        query getCards($cards : Int){
          getCards(cards: $cards){
            number
            symbol
          }
        }
      `,
      variables: {
        cards: 2
      }
    })
  })).json()

  return {
    props: {
      title: 'Cards.js',
      table: data.table, 
      hand: handData.data.getCards
    }
  }
}
